---
grails:
    profile: rest-api
    codegen:
        defaultPackage: dowork
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    jmx:
        unique-names: true
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false
    devtools:
        restart:
            additional-exclude:
                - '*.gsp'
                - '**/*.gsp'
                - '*.gson'
                - '**/*.gson'
                - 'logback.groovy'
                - '*.properties'
management:
    endpoints:
        enabled-by-default: false

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            json:
              - application/json
              - text/json   
            hal:
              - application/hal+json
              - application/hal+xml  
            xml:
              - text/xml
              - application/xml                                 
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            js: text/javascript
            rss: application/rss+xml
            text: text/plain
            all: '*/*'            
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        json:
            generator:
                dateFormat: "yyyy-MM-dd HH:mm:ss"
#                locale: "zh/CN"
                timeZone: "GMT+8"

---
hibernate:
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false
    dialect: org.hibernate.dialect.DmDialect
dataSource:
    pooled: true
    jmxExport: true
    driverClassName: dm.jdbc.driver.DmDriver
    username: IAGRAIN_STATION_A
    password: iag!ZTQK2020

environments:
    development:
        dataSource:
            dbCreate: none
            url: jdbc:dm://192.168.137.89:5236/DMSERVER
            logSql : true
    test:
        dataSource:
            dbCreate: none
            url: jdbc:dm://192.168.137.89:5236/DMSERVER
    production:
        dataSource:
            dbCreate: none
            url: jdbc:dm://192.168.137.89:5236/DMSERVER
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
